#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Derive the grouping thresholds (pdfwords.LayoutParams) from data.

Method (documented in docs/THRESHOLDS.md):
  * Data A - synthetic ground truth (tests/fixtures/synthetic.pdf/.json, generated by
    tools/make_synthetic.py): exact words, lines, blocks, superscripts and reading order.
  * Data B - real documents (tests/fixtures + tools/fetch_test_pdfs.py) scored for
    *output compatibility* against PyMuPDF's word/line/block output (black-box comparison;
    optional - skipped when pymupdf is not installed).
  * Score  S = mean(word F1, same-line pair accuracy, same-block pair accuracy,
               superscript F1, reading-order accuracy,
               fake-bold de-duplication accuracy)                     on A
           R = mean(word F1, same-line accuracy, same-block accuracy, superscript-char F1,
                    reading-order accuracy on LaTeX papers (content order == reading order)) on B
           Each threshold is optimised on the metric group it controls (METRIC_GROUPS):
           grouping thresholds on words/lines/blocks/fake-bold, superscript_rise on
           superscript F1, the XY-cut gaps on reading order; group objective = (S + R) / 2
           (S alone without pymupdf).
  * Start from neutral round values (START), then coordinate descent: for each threshold
    sweep its grid with the others fixed, find the contiguous plateau of grid values whose
    objective is within TOL of the best, and take the plateau's midpoint (robustness: the
    value farthest from where results start to degrade). Repeat ROUNDS times.

    python tools/tune_thresholds.py                    # full sweep, writes tools/tune_results.json
    python tools/tune_thresholds.py --eval             # score the current defaults only
"""
from __future__ import annotations

import argparse
import dataclasses
import difflib
import json
import multiprocessing as mp
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "python"))

import pypdfium2 as pdfium  # noqa: E402

from pdfwords.chars import page_glyphs  # noqa: E402
from pdfwords.layout import DEFAULT_PARAMS, LayoutParams, build_blocks, is_superscript  # noqa: E402
from pdfwords.order import sort_xycut  # noqa: E402
import fetch_test_pdfs  # noqa: E402

REAL = ["irs_w9.pdf", "simple_text.pdf", "table_camelot.pdf", "arxiv_attention.pdf", "arxiv_resnet.pdf"]
ORDER_DOCS = {"arxiv_attention.pdf", "arxiv_resnet.pdf"}  # LaTeX: content order == reading order
START = LayoutParams(word_gap=0.25, column_gap=1.0, baseline_tol=0.5, block_gap=2.0, dup_dist=0.25,
                     gen_space_min=0.0, indent_pt=1.0, superscript_rise=0.2, xycut_gap_x=10.0, xycut_gap_y=2.0)


def frange(a, b, step):
    n = int(round((b - a) / step))
    return [round(a + i * step, 4) for i in range(n + 1)]


GRIDS = {
    "word_gap": frange(0.02, 0.40, 0.01),
    "column_gap": frange(0.40, 3.00, 0.05),
    "baseline_tol": frange(0.10, 1.40, 0.05),
    "block_gap": frange(1.00, 3.00, 0.05),
    "dup_dist": frange(0.00, 0.60, 0.01),
    "gen_space_min": frange(-1.00, 0.30, 0.02),
    "indent_pt": frange(0.10, 12.00, 0.10),
    "superscript_rise": frange(0.00, 0.40, 0.01),
    "xycut_gap_x": frange(1.0, 30.0, 0.5),
    "xycut_gap_y": frange(0.25, 10.0, 0.25),
}
TOL = 0.0002

# each threshold is tuned on the metrics it controls
METRIC_GROUPS = {
    "grouping": {"synthetic": ["word_f1", "same_line", "same_block", "fake_bold"],
                 "real": ["word_f1", "same_line", "same_block"]},
    "superscript": {"synthetic": ["superscript_f1"], "real": ["superscript_f1"]},
    "order": {"synthetic": ["reading_order"], "real": ["reading_order"]},
}
PARAM_GROUP = {"superscript_rise": "superscript", "xycut_gap_x": "order", "xycut_gap_y": "order"}
ROUNDS = 2

_SYN = None   # [(glyphs, clip, gt_page)]
_REAL = None  # [(glyphs, clip, ref_words)]
_WS = set(" \t\n\r\u00a0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000")
LIG = {"\ufb00": "ff", "\ufb01": "fi", "\ufb02": "fl", "\ufb03": "ffi", "\ufb04": "ffl", "\ufb05": "st", "\ufb06": "st"}


def fold(t):
    return "".join(LIG.get(c, c) for c in t)


def _glyph_pages(path):
    pdf = pdfium.PdfDocument(path)
    out = []
    for i in range(len(pdf)):
        pg = pdf[i]
        tp = pg.get_textpage()
        g = page_glyphs(pg, tp)
        tp.close()
        from pdfwords.chars import crop_box
        l, b, r, t = crop_box(pg)
        out.append((g, (0, 0, abs(r - l), abs(t - b))))
    return out


def load_data(use_real=True):
    global _SYN, _REAL
    gt = json.load(open(os.path.join(ROOT, "tests", "fixtures", "synthetic.json")))
    pages = _glyph_pages(os.path.join(ROOT, "tests", "fixtures", "synthetic.pdf"))
    _SYN = [(g, c, p) for (g, c), p in zip(pages, gt["pages"])]
    _REAL = []
    if not use_real:
        return
    try:
        import pymupdf
    except ImportError:
        print("pymupdf not installed: tuning on synthetic ground truth only", file=sys.stderr)
        return
    for name in REAL:
        path = fetch_test_pdfs.path_of(name)
        if not path:
            print(f"skip {name} (not available)", file=sys.stderr)
            continue
        md = pymupdf.open(path)
        for (g, c), mp_page in zip(_glyph_pages(path), md):
            ref = [(fold(w[4]), (w[5], w[6]), w[5]) for w in mp_page.get_text("words")]
            sup = set()
            for b in mp_page.get_text("rawdict")["blocks"]:
                for ln in b.get("lines", ()):
                    for sp in ln["spans"]:
                        if sp["flags"] & 1:
                            sup.update(_okey(ch["origin"]) for ch in sp["chars"] if not ch["c"].isspace())
            _REAL.append((g, c, ref, sup, name in ORDER_DOCS))


def _okey(o):
    return (round(o[0] * 2), round(o[1] * 2))


def sup_chars(blocks, rise):
    out, allc = set(), set()
    for b in blocks:
        for ln in b.lines:
            for ch in ln.chars:
                if ch.synthetic or ch.c.isspace():
                    continue
                k = _okey(ch.origin)
                allc.add(k)
                if is_superscript(ln, ch, rise):
                    out.add(k)
    return out, allc


def content_order_score(blocks, sorted_blocks):
    """Fraction of content-consecutive block pairs that keep their relative order."""
    pos = {id(b): i for i, b in enumerate(sorted_blocks)}
    seq = [pos[id(b)] for b in blocks if b.lines]
    return sum(a < b for a, b in zip(seq, seq[1:])), max(0, len(seq) - 1)


def words_of(blocks):
    """[(text, line_key, block_key, has_superscript)] in output order (keys are object ids,
    so they are stable under reordering)."""
    out = []
    for b in blocks:
        bi = id(b)
        for ln in b.lines:
            li = id(ln)
            cur, sup = [], False
            for ch in ln.chars + [None]:
                if ch is None or ch.c in _WS:
                    if cur:
                        out.append(("".join(cur), li, bi, sup))
                        cur, sup = [], False
                    continue
                cur.append(ch.c)
                sup = sup or is_superscript(ln, ch, _RISE)
    return out


_RISE = 0.1


def pair_scores(ref, out, ref_line, ref_block, out_line, out_block):
    """word F1 + agreement of 'same line' / 'same block' on consecutive matched word pairs."""
    sm = difflib.SequenceMatcher(None, ref, out, autojunk=False)
    pairs = [(i1 + k, j1 + k) for t, i1, i2, j1, j2 in sm.get_opcodes() if t == "equal" for k in range(i2 - i1)]
    f1 = 2 * len(pairs) / max(1, len(ref) + len(out))
    sl = sb = nb = 0
    for (a0, b0), (a1, b1) in zip(pairs, pairs[1:]):
        sl += (ref_line[a0] == ref_line[a1]) == (out_line[b0] == out_line[b1])
        if ref_block[a0] is not None and ref_block[a1] is not None:
            nb += 1
            sb += (ref_block[a0] == ref_block[a1]) == (out_block[b0] == out_block[b1])
    n = max(1, len(pairs) - 1)
    return f1, sl / n, (sb / nb if nb else 1.0), pairs


def score(params: LayoutParams):
    global _RISE
    _RISE = params.superscript_rise
    # ---- A: synthetic ground truth
    acc = {"word_f1": [], "line": [], "block": [], "sup_tp": 0, "sup_fp": 0, "sup_fn": 0, "order": [],
           "fb_ok": 0, "fb_n": 0}
    wts = []
    for g, clip, gt in _SYN:
        blocks = build_blocks(g, clip, params)
        out = words_of(blocks)
        ref = [w[0] for w in gt["words"]]
        f1, sl, sb, pairs = pair_scores(ref, [w[0] for w in out], [w[1] for w in gt["words"]],
                                        [w[2] for w in gt["words"]], [w[1] for w in out], [w[2] for w in out])
        acc["word_f1"].append(f1); acc["line"].append(sl); acc["block"].append(sb); wts.append(len(ref))
        matched = {a for a, _ in pairs}
        for a in gt["fake_bold"]:
            acc["fb_n"] += 1
            acc["fb_ok"] += a in matched
        sup = set(gt["superscripts"])
        for a, b in pairs:
            if out[b][3] and a in sup:
                acc["sup_tp"] += 1
            elif out[b][3]:
                acc["sup_fp"] += 1
            elif a in sup:
                acc["sup_fn"] += 1
        if gt["kind"] == "two_column":
            ordered = words_of(sort_xycut(blocks, params.xycut_gap_x, params.xycut_gap_y))
            pos = {}
            # map ground-truth words to xycut output positions via the matched content-order pairs
            out_key = [(w[0], w[1]) for w in out]
            ord_index = {}
            for k, w in enumerate(ordered):
                ord_index.setdefault((w[0], w[1]), []).append(k)
            for a, b in pairs:
                lst = ord_index.get(out_key[b])
                if lst:
                    pos[a] = lst.pop(0)
            seq = sorted(pos, key=lambda a: gt["words"][a][3])
            good = sum(pos[x] < pos[y] for x, y in zip(seq, seq[1:]))
            acc["order"].append(good / max(1, len(seq) - 1))
    W = sum(wts)
    wavg = lambda xs: sum(x * w for x, w in zip(xs, wts)) / W  # noqa: E731
    tp, fp, fn = acc["sup_tp"], acc["sup_fp"], acc["sup_fn"]
    syn = {"word_f1": wavg(acc["word_f1"]), "same_line": wavg(acc["line"]), "same_block": wavg(acc["block"]),
           "superscript_f1": 2 * tp / max(1, 2 * tp + fp + fn),
           "reading_order": sum(acc["order"]) / max(1, len(acc["order"])),
           "fake_bold": acc["fb_ok"] / max(1, acc["fb_n"])}
    S = sum(syn.values()) / len(syn)
    groups = {}
    for g, keys in METRIC_GROUPS.items():
        groups[g] = {"S": sum(syn[k] for k in keys["synthetic"]) / len(keys["synthetic"])}
    # ---- B: compatibility with PyMuPDF output on real documents
    real = None
    R = None
    if _REAL:
        f1s, sls, sbs, ws = [], [], [], []
        stp = sfp = sfn = 0
        o_good = o_n = 0
        for g, clip, ref, rsup, order_doc in _REAL:
            if not ref:
                continue
            blocks = build_blocks(g, clip, params)
            osup, allc = sup_chars(blocks, params.superscript_rise)
            rsup = rsup & allc
            stp += len(osup & rsup); sfp += len(osup - rsup); sfn += len(rsup - osup)
            if order_doc:
                gd, n = content_order_score(blocks, sort_xycut(list(blocks), params.xycut_gap_x, params.xycut_gap_y))
                o_good += gd; o_n += n
            out = words_of(blocks)
            f1, sl, sb, _ = pair_scores([r[0] for r in ref], [fold(w[0]) for w in out], [r[1] for r in ref],
                                        [r[2] for r in ref], [w[1] for w in out], [w[2] for w in out])
            f1s.append(f1); sls.append(sl); sbs.append(sb); ws.append(len(ref))
        T = sum(ws)
        real = {k: sum(x * w for x, w in zip(v, ws)) / T for k, v in
                (("word_f1", f1s), ("same_line", sls), ("same_block", sbs))}
        real["superscript_f1"] = 2 * stp / max(1, 2 * stp + sfp + sfn)
        real["reading_order"] = o_good / max(1, o_n)
        R = sum(real.values()) / len(real)
        for g, keys in METRIC_GROUPS.items():
            groups[g]["R"] = sum(real[k] for k in keys["real"]) / len(keys["real"])
    for g in groups.values():
        g["objective"] = g["S"] if "R" not in g else (g["S"] + g["R"]) / 2
    obj = sum(g["objective"] for g in groups.values()) / len(groups)
    return {"objective": obj, "S": S, "R": R, "groups": groups, "synthetic": syn, "real": real}


def _eval(args):
    name, value, base = args
    p = dataclasses.replace(base, **{name: value})
    if p.block_gap <= p.baseline_tol:
        return value, -1.0
    return value, score(p)["groups"][PARAM_GROUP.get(name, "grouping")]["objective"]


def plateau_mid(grid, vals):
    best = max(vals)
    i = vals.index(best)
    lo = i
    while lo > 0 and vals[lo - 1] >= best - TOL:
        lo -= 1
    hi = i
    while hi < len(vals) - 1 and vals[hi + 1] >= best - TOL:
        hi += 1
    mid = grid[(lo + hi) // 2]
    return mid, grid[lo], grid[hi], best


def tune(pool):
    p = START
    history = []
    for rnd in range(ROUNDS):
        for name, grid in GRIDS.items():
            res = dict(pool.map(_eval, [(name, v, p) for v in grid]))
            vals = [res[v] for v in grid]
            mid, lo, hi, best = plateau_mid(grid, vals)
            p = dataclasses.replace(p, **{name: mid})
            history.append({"round": rnd + 1, "param": name, "chosen": mid, "plateau": [lo, hi], "best": round(best, 5),
                            "curve": [[v, round(x, 5)] for v, x in zip(grid, vals)]})
            print(f"round {rnd + 1} {name:17} -> {mid:<6} plateau [{lo}, {hi}]  objective {best:.5f}", flush=True)
    return p, history


def _init(use_real):
    load_data(use_real)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--eval", action="store_true", help="only score the current defaults (and the starting point)")
    ap.add_argument("--synthetic-only", action="store_true")
    ap.add_argument("-j", "--jobs", type=int, default=os.cpu_count())
    a = ap.parse_args()
    use_real = not a.synthetic_only
    load_data(use_real)
    t = time.time()
    report = {"start": dataclasses.asdict(START), "start_score": score(START),
              "defaults": dataclasses.asdict(DEFAULT_PARAMS), "defaults_score": score(DEFAULT_PARAMS)}
    if not a.eval:
        ctx = mp.get_context("fork") if hasattr(os, "fork") else mp.get_context()
        with ctx.Pool(a.jobs, initializer=_init, initargs=(use_real,)) as pool:
            best, hist = tune(pool)
        report.update({"tuned": dataclasses.asdict(best), "tuned_score": score(best), "history": hist,
                       "grids": {k: [v[0], v[-1], round(v[1] - v[0], 4)] for k, v in GRIDS.items()}, "tol": TOL})
        with open(os.path.join(ROOT, "tools", "tune_results.json"), "w") as f:
            json.dump(report, f, indent=1)
    for k in ("start", "defaults", "tuned"):
        if k in report:
            s = report[k + "_score"]
            gs = {g: round(v["objective"], 5) for g, v in s["groups"].items()}
            print(f"{k:9} groups={gs}  {json.dumps(report[k])}")
            print(f"{'':9} synthetic={json.dumps({x: round(y, 4) for x, y in s['synthetic'].items()})}")
            if s["real"]:
                print(f"{'':9} real={json.dumps({x: round(y, 4) for x, y in s['real'].items()})}")
    print(f"{time.time() - t:.1f}s")


if __name__ == "__main__":
    main()
